version: '3.5'

services: 
  angular-service:
    container_name: angular-container
    build: ./
    volumes: 
    - './:/usr/src/app'
    ports: 
      - '4200:4200'
    command: >
      bash -c "npm start"
    docker-nginx:
      container_name: docker-nginx
      build: ./
      ports: 
          - "80:80"
      command: ["nginx","ng","daemon off;"]
      links:
          - angular-service